name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Added'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Fixed'
    labels:
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
  - title: 'Dependency'
    labels:
      - 'dependency'
change-template: '- $TITLE (#$NUMBER) (@$AUTHOR)'
template: |
  ## What's Changed
  $CHANGES