version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: registrodb_n686  # Consistente con Render
      POSTGRES_USER: springuser     # Consistente con Render
      POSTGRES_PASSWORD: admin      # Para desarrollo local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/registrodb_n686
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: admin  # Para desarrollo local
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"        # true para desarrollo

volumes:
  postgres_data:
